version: 0.0  
os: linux  
files:  
  - source: /
    destination: /srv/mynodeapp
hooks:  
  ApplicationStop:
    - location: scripts/stopnode.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_nodeserver.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/MonitorService.sh
      timeout: 3600
      runas: root
