version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g
      - npm install express --save
      - npm install -g forever 
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
